### ISSUE TITLE
xquery tests module import at 

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/semver.xq#1]
How are we supposed to execute those?
After running `mvn clean package` all my tests still have `"file:///Users/aretter/code/semver.xq/src/main/xquery/semver.xq` as the import statement, that seems like a bug, and should my local path no?

**Comment by joewiz** [comment]
It would be nice to be able to run these via `mvn test`, but I'm not sure how to hook that up. Do we have that working for any other EXPath Packages like this - which are just library packages?

**Comment by duncdrum** [comment]
Not as far as I am aware: https://github.com/eXist-db/documentation/pull/291 and https://github.com/eXist-db/exist-apps-archetype/pull/15 are the current state afaik.

**Comment by joewiz** [comment]
With #3, we no longer have hardcoded references to module location.
